# Generated by Django 3.2.13 on 2022-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('pub_data', models.DateTimeField(verbose_name='data published')),
                ('thumbnail', models.ImageField(upload_to='image')),
            ],
        ),
    ]
