# Generated by Django 3.2.13 on 2022-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='pub_data',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumnail/%Y/%m/%d'),
        ),
    ]
